import fileinput
import os
import urllib.request

from py._builtin import execfile

url = (
    "https://raw.githubusercontent.com/Koenkk/zigbee-herdsman/"
    "v0.12.24/src/adapter/z-stack/znp/definition.ts"
)
target_path = "zigpy_cc/definition.py"

print("Download file...")
response = urllib.request.urlopen(url)
data = response.read()  # a `bytes` object
text = data.decode("utf-8")

ts_head = "\n".join(
    (
        "import {Subsystem, Type as CommandType} from '../unpi/constants';",
        "import ParameterType from './parameterType';",
        "import {MtCmd} from './tstype';",
        "",
        "const Definition: {",
        "    [s: number]: MtCmd[];",
        "}",
        "",
    )
)

py_head = "\n".join(
    (
        '"""',
        "GENERATED BY get_definitions.py",
        '"""',
        "from zigpy_cc.types import Subsystem, CommandType, ParameterType",
        "",
        "name = 'name'",
        "ID = 'ID'",
        "request = 'request'",
        "response = 'response'",
        "parameterType = 'parameterType'",
        "type = 'type'",
        "",
        "Definition ",
    )
)

ts_export = "export default Definition;"

print("Convert to python...")
text = text.replace(ts_head, py_head)
text = text.replace(ts_export, "")
text = text.replace("//", "#")
text = text.replace("    [Subsystem", "    Subsystem")
text = text.replace("]: [", ": [")

with open(target_path, "w") as text_file:
    text_file.write(text)

print("Check syntax...")
execfile(target_path)

print("Format with black...")
os.system("black " + target_path)

with fileinput.FileInput(target_path, inplace=True) as file:
    for line in file:
        line = line.replace("},],", "}],")
        line = line.replace("],},", "]},")
        print(line, end="")

print("Check syntax...")
execfile(target_path)

print("Success")
